[package]
name = "player-api-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
snake-api-lib = { path = "../snake-api-lib" }
strum = { version = "0.27.2", features = ["strum_macros"] }
strum_macros = "0.27.2"
itertools = { workspace = true }
ndarray = { workspace = true }
