[package]
name = "snake-api-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
bitvec = "1.0.1"
itertools = "0.14.0"
rand = "0.9.2"
strum = { version = "0.27.2", features = ["strum_macros"] }
strum_macros = "0.27.2"
ndarray = { workspace = true }
rayon = "1.11.0"
