[package]
name = "snake-api-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
bitvec = "1.0.1"
itertools = { workspace = true }
rand = { workspace = true }
strum = {workspace = true}
strum_macros = "0.27.2"
ndarray = { workspace = true }
rayon = "1.11.0"
